# Generated by Django 2.1.7 on 2019-06-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='goods',
            fields=[
                ('goods_id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_name', models.CharField(max_length=10)),
                ('goods_sort', models.CharField(max_length=10)),
                ('goods_num', models.CharField(max_length=10)),
                ('goods_remark', models.CharField(max_length=10)),
            ],
        ),
    ]
