# Generated by Django 2.1.7 on 2019-06-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='out_bill',
            fields=[
                ('out_id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_id', models.CharField(max_length=10)),
                ('storage_id', models.CharField(max_length=10)),
                ('subscriber_id', models.CharField(max_length=10)),
                ('goods_price', models.CharField(max_length=10)),
                ('goods_num', models.CharField(max_length=10)),
                ('out_data', models.DateField(max_length=10)),
            ],
        ),
    ]
